---
# whether mobs spawn at all
spawnmobs: true
# write spawn/despawn messages to the console
# this is noisy and mostly for debugging
spawnmsgs: false
# show name tags and health percent if percent is less than 100
damagetags: true
# regain this much health over time when idle
# setting to 0 disables
regainhealth: 1
# mobs will not spawn in any worldname containing one of these strings
nospawn:
- arena
- lobby
# amount of mobs to spawn of each type (higher numbers will use a lot more system resources)

# mobs list
mobs:
  Bat:
    amount: 3 # amount of mobs to spawn of each type
    drops: [] # items that drops when they killed
    exp: 1 # experience when they killed
  Blaze:
    amount: 3
    drops: []
    exp: 1
  Cat:
    amount: 3
    drops: []
    exp: 1
  CaveSpider:
    amount: 3
    drops: []
    exp: 1
  Chicken:
    amount: 3
    drops: []
    exp: 1
  Cod:
    amount: 3
    drops: []
    exp: 1
  Cow:
    amount: 3
    drops: []
    exp: 1
  Creeper:
    amount: 3
    drops: []
    exp: 1
  Dolphin:
    amount: 3
    drops: []
    exp: 1
  Donkey:
    amount: 3
    drops: []
    exp: 1
  ElderGuardian:
    amount: 3
    drops: []
    exp: 1
  Enderman:
    amount: 3
    drops: []
    exp: 1
  Ghast:
    amount: 3
    drops: []
    exp: 1
  Guardian:
    amount: 3
    drops: []
    exp: 1
  Horse:
    amount: 3
    drops: []
    exp: 1
  Husk:
    amount: 3
    drops: []
    exp: 1
  IronGolem:
    amount: 3
    drops: []
    exp: 1
  Llama:
    amount: 3
    drops: []
    exp: 1
  MagmaCube:
    amount: 3
    drops: []
    exp: 1
  Mooshroom:
    amount: 3
    drops: []
    exp: 1
  Ocelot:
    amount: 3
    drops: []
    exp: 1
  Parrot:
    amount: 3
    drops: []
    exp: 1
  Phantom:
    amount: 3
    drops: []
    exp: 1
  Pig:
    amount: 3
    drops: []
    exp: 1
  PolarBear:
    amount: 3
    drops: []
    exp: 1
  PufferFish:
    amount: 3
    drops: []
    exp: 1
  Rabbit:
    amount: 3
    drops: []
    exp: 1
  Salmon:
    amount: 3
    drops: []
    exp: 1
  Sheep:
    amount: 3
    drops: []
    exp: 1
  Silverfish:
    amount: 3
    drops: []
    exp: 1
  Skeleton:
    amount: 3
    drops: []
    exp: 1
  SkeletonHorse:
    amount: 3
    drops: []
    exp: 1
  Slime:
    amount: 3
    drops: []
    exp: 1
  Spider:
    amount: 3
    drops: []
    exp: 1
  Squid:
    amount: 3
    drops: []
    exp: 1
  Stray:
    amount: 3
    drops: []
    exp: 1
  TropicalFish:
    amount: 3
    drops: []
    exp: 1
  Villager:
    amount: 3
    drops: []
    exp: 1
  Witch:
    amount: 3
    drops: []
    exp: 1
  Wolf:
    amount: 3
    drops: []
    exp: 1
  Zombie:
    amount: 3
    drops: []
    exp: 1
  ZombieVillager:
    amount: 3
    drops: []
    exp: 1

...
